### ISSUE TITLE
A problem with goto.... [13%] Building CXX object CMakeFiles/vermilion.dir/lib/vdds.cpp.o

### ISSUE THREAD

**Issue by MihaiGaidau** [openglredbook/examples#15]
I run make, on Unix Makefile on Ubuntu,

I got this error:
lib/vdds.cpp:645:1: error: jump to label ‘done_close_file’ [-fpermissive]

How can I avoid it?, please help

**Comment by bclinthall** [comment]
I'm having the same problem. @elmindreda fixed this in her/his fork here: https://github.com/elmindreda/examples. It's also pull request #5.

**Comment by D-K-E** [comment]
I can also verify that elmindreda fix works on Ubuntu 16.04 with option "Unix Makefiles"

**Comment by jackson-elfers** [comment]
Same issue thanks!

**Comment by RYNEQ** [comment]
I have same problem in ubuntu 18.04  
I tried `cmake -DCMAKE_CXX_FLAGS=-fpermissive ..` made that error disappear but now I get:     

```
In file included from /home/ryn/Desktop/examples/lib/vermilion.cpp:1:0:
/home/ryn/Desktop/examples/include/vapp.h:18:21: error: field ‘m_appStartTime’ has incomplete type ‘timeval’
     struct timeval  m_appStartTime;
                     ^~~~~~~~~~~~~~
/home/ryn/Desktop/examples/include/vapp.h:18:12: note: forward declaration of ‘struct timeval’
     struct timeval  m_appStartTime;
            ^~~~~~~
/home/ryn/Desktop/examples/lib/vermilion.cpp: In member function ‘virtual void VermilionApplication::Initialize(const char*)’:
/home/ryn/Desktop/examples/lib/vermilion.cpp:42:5: error: ‘gettimeofday’ was not declared in this scope
     gettimeofday(&m_appStartTime, nullptr);
     ^~~~~~~~~~~~

```

Any solution?

**Comment by AstroWYH** [comment]
i have the same problem and i'm trying elmindreda's fork.
